import './my_que_model.dart';

class MyQueList {
  List<MyQueModel> queList = [
    MyQueModel(
      'A try block can be followed by?',
      'catch block',
      'finally block',
      'Neither a nor b',
      'Both a & b',
      'op4',
      'CPS101',
      false,
      false,
      false,
      0,
      0,
    ),
    MyQueModel(
      'Which of the following is the top level class in JAVA exception handling?',
      'Throwable',
      'Exception',
      'RuntimeException',
      'Error',
      'op1',
      'CPS102',
      false,
      false,
      false,
      0,
      0,
    ),
    MyQueModel(
      'ArithmeticException is .......?',
      'Unchecked exception',
      'Checked exception',
      'User defined exception',
      'Not thrown automatically',
      'op1',
      'CPS103',
      false,
      false,
      false,
      0,
      0,
    ),
    MyQueModel(
      'Which of the following is not a built-in exception class type?',
      'Unchecked',
      'RuntimeException',
      'Exception',
      'ArithmeticException',
      'op1',
      'CPS104',
      false,
      false,
      false,
      0,
      0,
    ),
    MyQueModel(
      'We have to catch 1)ArithmeticException, 2)Exception, 3)RuntimeException class type exceptions; What should be the order of corresponding catch clauses immediately following the try{} block?',
      '1 - 2 - 3',
      '1 - 3 - 2',
      '3 - 2 - 1',
      'None of the above',
      'op2',
      'CPS105',
      false,
      false,
      false,
      0,
      0,
    ),
  ];
}
